feat(index): update style to sciwork theme
sciwork/COSCUP-Volunteer pull request #1
Opened 2024-06-12 03:41 UTC by rockleona

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Previous landing page (index.html) had COSCUP style and words.

## What is the new behavior?

- Update landing page with sciwork style

## Other information

2024-06-12 03:43 UTC, rockleona commented
Here is the preview of the change:

<details>
<summary>Screenshot</summary>

![image](https://github.com/sciwork/COSCUP-Volunteer/assets/34214497/658254ca-4079-48ec-84cf-5ef157c6e8fb)

</details>

2024-06-15 04:38 UTC, chestercheng requested changes
* I have created the dev branch as the default branch, so please change the base to it.
* I think we can temporarily remove the “About Volunteer Groups” and “Calendar” sections on the index page.
* The “About sciwork” section still mentions COSCUP. Please correct it and use the content from our portal instead.

2024-06-19 03:44 UTC, rockleona commented
> * I have created the dev branch as the default branch, so please change the base to it.
> * I think we can temporarily remove the “About Volunteer Groups” and “Calendar” sections on the index page.
> * The “About sciwork” section still mentions COSCUP. Please correct it and use the content from our portal instead.

Hi @chestercheng, I already push a commit with your suggestion, please review

2024-06-19 12:08 UTC, chestercheng requested changes

2024-06-19 12:08 UTC, chestercheng commented on templates/index.html
>                          <a href="https://coscup.org/"
there is a typo, it should be https://sciwork.dev

2024-06-25 12:04 UTC, chestercheng approved these changes
LGTM

2024-07-15 06:39 UTC, chestercheng commented
Since we will redesign the UI, I think this PR can be closed

2024-07-15 06:39 UTC, closed without merging